CREATE TABLESPACE VRAJ_OWNER_PERM_01
DATAFILE 'VRAJ_OWNER_PERM_01.dat' 
SIZE 50M
ONLINE;

CREATE USER VRAJ_OWNER
IDENTIFIED BY VRAJ_OWNER
DEFAULT TABLESPACE VRAJ_OWNER_PERM_01
QUOTA 50M on VRAJ_OWNER_PERM_01;

GRANT create session TO VRAJ_OWNER;
GRANT create table TO VRAJ_OWNER;
GRANT create view TO VRAJ_OWNER;
GRANT create any trigger TO VRAJ_OWNER;
GRANT create any procedure TO VRAJ_OWNER;
GRANT create sequence TO VRAJ_OWNER;
GRANT create synonym TO VRAJ_OWNER;