-- Create Table Space
CREATE TABLESPACE VRAJ_OWNER_PERM_01
DATAFILE 'VRAJ_OWNER_PERM_01.dat' 
SIZE 50M
ONLINE;

-- Create User 
CREATE USER VRAJ_OWNER
IDENTIFIED BY VRAJ_OWNER
DEFAULT TABLESPACE VRAJ_OWNER_PERM_01
QUOTA 50M on VRAJ_OWNER_PERM_01;

-- All Grants
GRANT create session TO VRAJ_OWNER;
GRANT create table TO VRAJ_OWNER;
GRANT create view TO VRAJ_OWNER;
GRANT create any trigger TO VRAJ_OWNER;
GRANT create any procedure TO VRAJ_OWNER;
GRANT create sequence TO VRAJ_OWNER;
GRANT create synonym TO VRAJ_OWNER;

-- Create table
DROP TABLE VRAJ_OWNER.TEMP_TABLE1;
CREATE TABLE VRAJ_OWNER.TEMP_TABLE1 (
	TEMP_ID CHAR(6) NOT NULL, 
	SEGMENT_NUMBER INT NOT NULL,
	TEMP_DATE DATE NOT NULL, 
	TEMP_IS_TAKEN INT,
	TEMP_NAME VARCHAR2(30), 
	TEMP_ADDRESS VARCHAR2(100), 
	CONSTRAINT TEMP_TABLE1_PK
	PRIMARY KEY (TEMP_ID, TEMP_NAME));

DROP TABLE VRAJ_OWNER.TEMP_TABLE2;
CREATE TABLE VRAJ_OWNER.TEMP_TABLE2 (
	TEMP_ID CHAR(6) NOT NULL, 
	SEGMENT_NUMBER INT NOT NULL,
	TEMP_DATE DATE NOT NULL, 
	TEMP_NAME VARCHAR2(30),
	CONSTRAINT TEMP_TABLE2_PK
	PRIMARY KEY (TEMP_ID, TEMP_NAME));
